# Basic Information
baseURL = "https://thuyetbao.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"

# Novela settings
theme = "gatsby-theme-novela"

paginate = 6

[social]
twitter= "https://github.com/thuyetbao"
github= "https://github.com/thuyetbao"
linkedin= "https://www.linkedin.com/in/thuyetbao/"
instagram = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "Thuyet Bao"
